- task: AzureWebApp@1
  inputs:
    appType: 'webAppLinux'
    appName: 'T2UXTWEB'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo - task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'T2UXTSERVER'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'Run a multi-line script'
